Added documentation on SNS
CS-6381/FinalProject pull request #8
Opened 2021-04-01 03:10 UTC by tesmonrd

Included specs on AWS SNS in a readme under the SNS directory in Messaging Queue

2021-04-03 22:22 UTC, jmbeach approved these changes

2021-04-03 22:23 UTC, jmbeach requested changes
Can you remove the ".gitkeep" files?

2021-04-07 23:57 UTC, TheENGR approved these changes

2021-04-12 22:54 UTC, jmbeach approved these changes

2021-04-12 22:54 UTC, merged